server:
  port: 8081
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

portal:
  id: ${PORTAL_ID}
  pwd: ${PORTAL_PWD}
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}



