server:
  port: 9000
  servlet:
    context-path: /

spring:
  datasource:
    url: ENC(EJ1jFIX2q4UiZTSWRu0ZTPZzKGlmijV2kk6p65cJNrvW3Y3krF4khvDoifFYSKD6X8U1JH+WGMvlJafTyt1RV1g7IO/ZHt3tnYgcyYOiIveWNcuqXBQoJLK7Ma+/X97bSlrSQcQOc52z/vxVk/Ur7Q==)
    username: ENC(aGHYR63qef6rzq/iQjziTA==)
    password: ENC(FWKWzF73KODPLiwC0l36gq48cIgaitQA)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: none

portal:
  id: ENC(Z6HpAscjxxVoGxEdwr1P3w==)
  pwd: ENC(Lzc6O4kHIQDx5IfHFjhYsJlhXKuxPaJJ)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

checku:
  url: ENC(nPNUhvugiZeCjj7DB5GpflSqDOSto9wziqI8xvCpE6YJZuUTLFNVGw==)



